[package]
name = "b3"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
[dependencies]
tinyvec = { version = "1.6", features = ["alloc"] }
num = "0.4"
macroassembler = { path = "masm-rs" }
once_cell = "1.8"
paste = "1.0"
indexmap = "1.9"
libc = "0.2"
pico-args = "0.5"

[features]
default = ["graph-coloring-briggs"]

graph-coloring-briggs = []
graph-coloring-irc = []