[package]
name = "b3"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
[dependencies]
tinyvec = { version = "1.6", features = ["alloc"] }
num = "0.4"
macroassembler = { git = "https://github.com/playxe/masm-rs" }
paste = "1.0"
bitvec = "1.0"